### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [KapSSe/site-tajem#1]
1. Пукнты меню никуда не ведут
1. Лишняя линка в меню, скорее тег не закрыл предыдущий http://joxi.ru/Q2K0aBpu4G6lXA
1. Колонки должны были быть на одном уровне, а не оббернута в nav, и только там я нахожу col-sm-10 http://joxi.ru/brRYkpluJdRvpA
1. Мне не сильно нравится, когда ты ограничиваешь так четко в пикселях, хотя у тебя есть бутстрап и offset http://joxi.ru/E2pbN9df9JpPBr
1. мне кажется, что тебе надо было не эту штуку вводить, а какие-то отступы всем `.sc` в виде padding добавить, а уже отдельно некоторым чуть больше сделать http://joxi.ru/xAe5RO1hpa8klA
1. Горизонтальный скролл http://joxi.ru/1A5WOaztnO6XOm
1. Нижняя форма не в теге `<form>` почему
1. Как-то много тегов и есть пустые http://joxi.ru/eAODnN7sxqK5gr

**Comment by KapSSe** [comment]
1.Исправил/добавил smooth scroll.
2.Исправил.
3.Да не логично было совсем. Исправил. Теперь на одном уровне а внутри уже nav.
4.Убрал ограничение в пикселях.
5.Точно! Я забыл что padding-ом можно. Поправил.
6.Исправил.
7.Из за невнимательности, исправил. Я ей даже класс "form" ставил(
8.Убрал пустые.
9. + доделал карусель внизу и галерею.
